### ISSUE TITLE
Spurious test-case failures related to string merging

### ISSUE THREAD

**Issue by marxin** [davidlattimore/wild#259]
Pretty rarely, but surely, I hit the following issue for various test-cases:

```
$ cargo clean
$ cargo test --release
Error: Failed copying from /usr/lib64/gcc/x86_64-suse-linux/14/../../../../lib64/crt1.o (256 (1/0)) to output file

Caused by:
    0: Failed to apply relocations in section `.debug_info` of /usr/lib64/gcc/x86_64-suse-linux/14/../../../../lib64/crt1.o
    1: Failed to apply relocation of type R_X86_64_32 to section `.debug_str` (23 local=13) in file #256 (1/0) (/usr/lib64/gcc/x86_64-suse-linux/14/../../../../lib64/crt1.o) (ADDRESS | CAN_BYPASS_GOT) at offset 0x1a
    2: Failed to find merge-string at offset 0
test integration_test::program_name_31___input_does_not_exist_c__ ... ok
collect2: error: ld returned 255 exit status
test integration_test::program_name_02___trivial_main_c__ ... FAILED
```

I also hit the same issue in dev mode sometimes:
```
Error: Failed copying from /usr/lib64/gcc/x86_64-suse-linux/14/../../../../lib64/crt1.o (256 (1/0)) to output file

Caused by:
    0: Failed to apply relocations in section `.debug_info` of /usr/lib64/gcc/x86_64-suse-linux/14/../../../../lib64/crt1.o
    1: Failed to apply relocation of type R_X86_64_32 to section `.debug_line_str` (24 local=14) in file #256 (1/0) (/usr/lib64/gcc/x86_64-suse-linux/14/../../../../lib64/crt1.o) (ADDRESS | CAN_BYPASS_GOT) at offset 0x4b
    2: Failed to find merge-string at offset 112
collect2: error: ld returned 255 exit status
test integration_test::program_name_29___cpp_integration_cc__ ... FAILED
```

Typically happens if I run cargo clean and then completely rebuild the `wild` linker. This might be related to: #249.

**Comment by marxin** [comment]
Pretty common in the debug mode as well:

```
❯ for t in {0..30} ; do echo $t ; cargo t 2>&1 | grep -B5 -A5 merge-string ; done
0
1
2
3
4
5
6
7
8
9
Make sure unwinding works
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /home/marxin/Programming/wild/wild/tests/sources/rust-integration.rs:21:5:
Make sure unwinding works
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Failed to find merge-string at offset 16640
collect2: error: ld returned 255 exit status
test integration_test::program_name_26___libc_integration_c__ ... FAILED
test integration_test::program_name_28___rust_integration_dynamic_rs__ ... ok
thread 'main' panicked at /home/marxin/Programming/wild/wild/tests/sources/rust-integration.rs:21:5:
Make sure unwinding works
10
11
12
13
14
15
16
17
18
19
Error: Failed copying from /usr/lib64/gcc/x86_64-suse-linux/14/../../../../lib64/crt1.o (256 (1/0)) to output file

Caused by:
    0: Failed to apply relocations in section `.debug_info` of /usr/lib64/gcc/x86_64-suse-linux/14/../../../../lib64/crt1.o
    1: Failed to apply relocation of type R_X86_64_32 to section `.debug_line_str` (24 local=14) in file #256 (1/0) (/usr/lib64/gcc/x86_64-suse-linux/14/../../../../lib64/crt1.o) (ADDRESS | CAN_BYPASS_GOT) at offset 0x4b
    2: Failed to find merge-string at offset 112
collect2: error: ld returned 255 exit status
test integration_test::program_name_29___cpp_integration_cc__ ... FAILED
thread 'main' panicked at /home/marxin/Programming/wild/wild/tests/sources/rust-integration.rs:21:5:
Make sure unwinding works
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
20
21
22
23
24
25
26
27
Error: Failed copying from /usr/lib64/gcc/x86_64-suse-linux/14/../../../../lib64/crt1.o (256 (1/0)) to output file

Caused by:
    0: Failed to apply relocations in section `.debug_info` of /usr/lib64/gcc/x86_64-suse-linux/14/../../../../lib64/crt1.o
    1: Failed to apply relocation of type R_X86_64_32 to section `.debug_str` (23 local=13) in file #256 (1/0) (/usr/lib64/gcc/x86_64-suse-linux/14/../../../../lib64/crt1.o) (ADDRESS | CAN_BYPASS_GOT) at offset 0x1a
    2: Failed to find merge-string at offset 0
collect2: error: ld returned 255 exit status
test integration_test::program_name_29___cpp_integration_cc__ ... FAILED
thread 'main' panicked at /home/marxin/Programming/wild/wild/tests/sources/rust-integration.rs:21:5:
Make sure unwinding works
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
28
29
30
```

**Comment by davidlattimore** [comment]
I assume this has only started happening since I changed the string merge algorithm - i.e in the last day?

**Comment by marxin** [comment]
Yes, started with 190bec9.

**Comment by marxin** [comment]
Got fixed with the just landed changes related to string merging.
